### ISSUE TITLE
I don't think anyone is using this app, but...

### ISSUE THREAD

**Issue by ashakoen** [ashakoen/next-js-flux1-replicate#2]
It's about to become much more about a personal passion/art project than a general image gen utility. Lots of changes coming in the next week or two that will make this app more about what I want and need it to do than anything else. Just putting this here for historical purposes. Enjoy!

**Comment by kittenlogic** [comment]
I just downloaded your app. It's great! Love that you can save prompts. Any chance you will be adding more models? Just tried flux-1.1-pro-ultra and 😍. Thank you so much for sharing this project!

**Comment by ashakoen** [comment]
> I just downloaded your app. It's great! Love that you can save prompts. Any chance you will be adding more models? Just tried flux-1.1-pro-ultra and 😍. Thank you so much for sharing this project!

Glad you like it. I just added flux-1.1-pro and ultra!
